pull request feature spam notification on IOS
gdelataillade/alarm pull request #199
Opened 2024-05-07 08:32 UTC by Atsug0

FEATURE :

When the app is killed on IOS we can add a spam of X notification with a certain delay, you can custom the sound of the notification by adding a sound of less than 30sec on your IOS project (see in the exemple with marimba.mp3)

2024-05-07 09:57 UTC, gdelataillade requested changes

2024-05-07 09:57 UTC, gdelataillade commented on example/ios/Runner.xcodeproj/project.pbxproj
> +		7484BE252BE9100400D9AC5F /* marimba.mp3 in Resources */ = {isa = PBXBuildFile; fileRef = 7484BE242BE9100400D9AC5F /* marimba.mp3 */; };
Il faudrait pas qu'il y ait d'audio importé dans le projet car il faudrait que ça puisse être n'importe quel audio et non un audio prédéfini.

2024-05-07 09:57 UTC, gdelataillade commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.gdelataillade.alarm.alarmExample12;
Pourquoi le bundle id a été changé ?

2024-05-07 09:57 UTC, gdelataillade commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LUU9F35TKJ;
Faut pas que tu push ça.

2024-05-07 09:57 UTC, gdelataillade commented on example/ios/Runner.xcodeproj/project.pbxproj
Il faudrait pas que ce fichier soit modifié.

2024-05-07 09:57 UTC, gdelataillade commented on example/lib/screens/edit_alarm.dart
> +        notificationSound: 'marimba.mp3');
Il manque le [trailing comma](https://dart.dev/tools/linter-rules/require_trailing_commas).

2024-05-07 09:57 UTC, gdelataillade commented on ios/Classes/SwiftAlarmPlugin.swift
> +    // Obtenez la date et l'heure actuelles
Faut éviter tout les commentaires en français comme c'est une projet open source.

2024-05-07 09:57 UTC, gdelataillade commented on ios/Classes/services/NotificationManager.swift
> +    func programLocalNotif(nbrOfRepeat: Int = 10, duration: Int = 10,hour: Int, minute: Int, title: String, body: String, sound: UNNotificationSound?) {
Pas besoin d'avoir la doc sur les paramètres ici.

2024-05-07 09:57 UTC, gdelataillade commented on ios/Classes/services/NotificationManager.swift
> +                    // ADD the Flutter log here to catch the error with a message like: "Something went wrong in the local notifications programming [notif\(indexOf Notif)]"
Il manque quelque chose ?

2024-05-07 09:57 UTC, gdelataillade commented on ios/Classes/services/NotificationManager.swift
> +    /// - Returns: The full and effective date of triggering the notification
Pas besoin d'avoir la doc sur les paramètres ici non plus.

2024-05-07 09:57 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +    this.notificationSound = "",
Je trouve que les noms des paramètres ne sont pas clairs. `nbrOfRepeat` on sait pas ce que c'est si on connait pas. `duration` et `notificationSound` non plus. D'ailleurs `notificationSound` ça doit pas être le meme que `assetAudioPath` ?

2024-05-07 09:57 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +      notificationSound: json['notificationSound'] as String? ?? '');
Il manque le [trailing comma](https://dart.dev/tools/linter-rules/require_trailing_commas).

2024-05-07 10:18 UTC, Atsug0 commented on lib/model/alarm_settings.dart
> +    this.notificationSound = "",
notificationSound et assetAudioPath ne sont pas forcément les mêmes car notificationSound doit être le path d'une musique qui à été importé dans le projet xcode

2024-05-07 10:29 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +    this.notificationSound = "",
Mais normalement il y a pas besoin d'importer des assets dans Xcode. L'audio de la spam notification doit être dynamique.

2024-05-07 10:33 UTC, gdelataillade requested changes

2024-05-07 10:33 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +    this.notificationSound = "",
Je trouve que ça fait trop de paramètres différents pour une feature assez spécifique. J'aurais plutôt créé un model genre `IOSSpamNotificationSettings` qui prend la config.

2024-05-07 11:43 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +    this.notificationSound = "",
Pour la notification de l'alarme j'ai pas du importer de sons avec Xcode.

2024-05-07 12:22 UTC, gdelataillade requested changes

2024-05-07 12:22 UTC, gdelataillade commented on lib/model/alarm_settings.dart
> +class IOSSpamNotificationSettings {
Faudrait mettre cette class dans un ficher à part dans `src/model/`.

2025-02-07 07:38 UTC, SungjunApp reviewed
Hi, thank you for your plugin. 

Since there is a limit of setting maximum 64 notifications in iOS, do you think it is possible to set repeatedly showing notification until the user opens the app when the alarm reaches the time? Several alarm apps on AppStore such as Alarmy, Alarmer and AlarmMon provides this functionality. 

fyi, one thing I noticed is that their notification that repeat every 1-5 seconds have the same message.

2025-02-07 15:59 UTC, gdelataillade commented
> Hi, thank you for your plugin.
> 
> Since there is a limit of setting maximum 64 notifications in iOS, do you think it is possible to set repeatedly showing notification until the user opens the app when the alarm reaches the alarm's target time? Several alarm apps on AppStore such as Alarmy, Alarmer and AlarmMon provides this functionality.
> 
> fyi, one thing I noticed is that their notifications that repeat every 1-5 seconds have the same message. This could mean that they got triggered by something and using interval trigger, notification could repeat. This works after the app gets killed.

Yes it should be possible. I'll add it to my to-do list !

2025-02-07 15:59 UTC, closed without merging

2025-02-08 05:00 UTC, SungjunApp commented
I appreciate it. Have a good weekend.